<div class="max-w-7xl mx-auto">
    <h2>Rules</h2>
    <h3>Entry</h3>
    <ul class="pl-8 list-disc">
        <li>
            The maximum team size is 4. Any bigger, and we might have to split
            you up. Solo participation is allowed, but hacking is better with
            other people!
        </li>
        <li>
            Due to departmental rules, participants must be students at the
            University of Cambridge.
        </li>
    </ul>
    <h3>House rules</h3>
    <ul class="pl-8 list-disc">
        <li>
            Please do not bring food into the Intel lab! All food must stay
            downstairs in the street. &#127829;
        </li>
        <li>You must not bring or consume alcohol at the hackathon.</li>
        <li>
            We don't recommend it, but you can stay overnight in the lab if you
            want. &#128564;
        </li>
        <li>
            All participants must follow our <a
                href="/code-of-conduct"
                class="theme-hyperlink">Code of Conduct</a
            >.
        </li>
    </ul>
    <h3>Submission</h3>
    <ul class="pl-8 list-disc">
        <li>
            All work on projects must be done at the hackathon. Using existing
            open source code is allowed if credited, but the project should be
            substantially new.
        </li>
        <li>
            Working on a project and open sourcing it for the sole purpose of
            using the code in the hackathon is against the spirit of the rules
            and is not allowed.
        </li>
        <li>
            AI assistants (Copilot, ChatGPT, etc.) are allowed when writing
            code, but don't go overboard. For example, using AI assistants as a
            tool to help you code is fine, but asking one to generate a whole
            website or the core logic of your application is not allowed. Images
            generated by external (not part of your project) AI models must be
            credited, but such use is discouraged.
        </li>
        <li>
            After hacking finishes, representatives for each track will go
            around to look at each demo. You are free to look at other projects,
            as long as one team member is available to present a demo of their
            project.
        </li>
        <li>
            If you discover a breaking bug during your demo with a trivial fix,
            that's okay to rectify. &#128027;
        </li>
        <li>
            Submissions will be made to <a
                href="https://cam-hack-2024.devpost.com"
                class="theme-hyperlink">Devpost</a
            >.
        </li>
    </ul>
</div>
